# -*- coding: utf-8 -*-
"""Prasad Kulkarni DEPT of MBA KLS GIT Python workbook

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rYer6AhddNXNB66mZ7C2tjqYo8Msr9Om
"""

print("Hello Python")

print ("Hello Python")

if True:
 print ("True")
else:
 print ("False")

if True:
  print("True")
else:
  print("False")

if True:
  print("Answer")
  print("True")
else:
        print(" Answer")
        print("False")

counter=100 # an integer
mile=100.5  # a float number
name="Gogte" # a string
print(counter)
print(mile)
print(name)

a=b=c=1

a,b,c=2,3,4
print(a)
print(a,b)
print(a,b,c)

# working with strings
str="Prasad Kulkarni"
print (str[0])
print(str[1])
print(str[2])
print(str[:2])
print(str[2:])
print(str[:3])
print (str[3:])
print(str[2:5])
print(str[6:12])
print(str[6:15])
print(str*2)
print(str+'Test')

# Working with list
India=[13,17,19,"Country'"," Nature", 32,13.5]
print(India[0])
print(India[:2])
print(India[2:])
print(India[2:5])
print(India*2)

# working with tuples
Karnataka=('state',"Belagavi",1,2,24,5,7)
print(Karnataka)
print(Karnataka[1:3])
print(Karnataka[3:])

# working with dictionaries
dict={}
dict ['One']= "This is one"
print(One)
dict[2]="This is two"
print(dict[2])
tinydict={'Name':'John','Dept':'MBA', 'Code': 23}
print(tinydict)
print (tinydict.keys())
print(tinydict.values())

x=12
int=int(x)
print(int)

# converting objects to a string representation.
x=14
y=str(x)
print(y)

# Module basic operator and calculate addition
a=2
b=3
c=2
d=a+b+c
print("the total of a,b,c is",d)

# basic operator and calculation of substraction
a=45
b=24
c=a-b
print("the difference of two numbers is",c)

#basic oeprator and calcuation of multiplication
a=15
b=23
c=a*b
print(" the product of two numbers are",c)

# Basic operator and calculation of division
x=456
y=231
z=x/y
print(" The reminder of two numbers is",z)

# comparision operators or relational operators if two operators are equal and result will becometrue
a=25
b=14
if(a==b):
  print("a is equal to b")
else:
  print("a is not equal to b")

# operator for getting true results when conditions are not equal as true
a=12
b=56
if (a!=b):
  print("a is not equal to b")
else:
  print("a is equal to b")

# larger and condition become true
x=234
y=145
if x>y:
  print("x is greater than y")
else:
  print("x is smaller than y")

# smaller and condition operator become true
x=234
y=145
if x<y:
  print("x is greater than y")
else:
  print("x is smaller than y")

# greater than or equals to
x=222
y=111
if x>= y:
  print(" x is greater than or equal to y")
else:
  print(" x is not greater than or equal to y")

# lesser than or equal to
x=145
y=123
if x<= y:
  print(" x is greater than or equal to y")
else:
  print(" x is not greater than or equal to y")